# Supported languages: chs | kor | eng | rus | spa
# 如果你想自定义语言文件请设置为xxx_customize, 例如chs_customize 并修改chs_customize.yml文件
# If you want to customize the language file, please set it to xxx_customize, such as eng_customize and modify the eng_customize.yml file
language: chs
restoreWorld: true
#在游戏内使用单独血量计算（Boss血条显示自身血量）
#适合RPG或其他会修改玩家血量的服务器使用
enableAloneHealth: true
#允许非GunWar插件武器造成的伤害
enableOtherWeaponDamage: false
cmdUser: gunwar
cmdAdmin: gunwaradmin
#可以在游戏房间中使用的命令
cmdWhitelist:
  - ban
  - kick
  - report
胜利执行命令:
  - me 我胜利了
  - tell "@p" 恭喜获得胜利！&con
失败执行命令:
  - me 我失败了
  - tell "@p" 很遗憾你失败了！&con

QuitRoom:
  #退出房间执行命令
  cmd: []

#游戏内积分 （商店用）
integral:
  #游戏开始时玩家基础积分
  Start_Base_Integral: 1000
  #击杀敌人获得积分
  Kill_Score: 10
  #击杀队友获得积分
  Kill_Team_Score: -10
  #安放炸弹获得积分 （仅爆破模式）
  Bomb_Score: 20
  #拆除炸弹获得积分 （仅爆破模式）
  Destroy_Score: 20
  #运回旗帜获得积分 （仅限夺旗模式）
  Flag_Get_Score: 20
  #回合胜利获得积分
  Round_Win_Score: 100
  #回合失败获得积分
  Round_Lose_Score: 50