# chs | kor | eng | rus | spa
language: chs
restoreWorld: true
#在游戏内使用单独血量计算（Boss血条显示自身血量）
#适合RPG或其他会修改玩家血量的服务器使用
enableAloneHealth: true
#允许非GunWar插件武器造成的伤害
enableOtherWeaponDamage: false
cmdUser: gunwar
cmdAdmin: gunwaradmin
#可以在游戏房间中使用的命令
cmdWhitelist:
  - ban
  - kick
  - report
胜利执行命令:
  - me 我胜利了
  - tell "@p" 恭喜获得胜利！&con
失败执行命令:
  - me 我失败了
  - tell "@p" 很遗憾你失败了！&con

#游戏内积分 （商店用）
integral:
  #击杀敌人获得积分
  KILL_SCORE: 10
  #安放炸弹获得积分 （仅爆破模式）
  BOMB_SCORE: 20
  #拆除炸弹获得积分 （仅爆破模式）
  DESTROY_SCORE: 20
  #回合胜利获得积分
  ROUND_WIN_SCORE: 100
  #回合失败获得积分
  ROUND_LOSE_SCORE: 50