name: GunWar
main: cn.lanink.gunwar.GunWar
version: "1.7.3"
api: ["1.0.11"]
load: POSTWORLD
author: "LT_Name"
website: "https://www.lanink.cn"
depend:
  - "MemoriesOfTime-GameCore"

permissions:
  GunWar.command.user:
    description: "GunWar 命令"
    default: true
  GunWar.command.admin:
    description: "GunWar 管理命令"
    default: op