name: GunWar
main: cn.lanink.gunwar.GunWar
version: "0.0.1-SNAPSHOT"
api:
  - 1.0.0
load: POSTWORLD
author: "LT_Name"
depend:
  - "Tips"
loadbefore:
  - EconomyAPI

permissions:
  GunWar.command.user:
    description: "GunWar 命令"
    default: true
  GunWar.command.admin:
    description: "GunWar 管理命令"
    default: op