package cn.lanink.gunwar.gui;

public enum GuiType {
    USER_MENU,
    ADMIN_MENU,
    ADMIN_CREATE_ROOM_MENU,
    ADMIN_SET_ROOM_MENU,
    ADMIN_TIME_MENU,
    ADMIN_PLAYERS_MENU,
    ADMIN_MODE_MENU,

    ADMIN_ITEM_ADD_WEAPON,
    ADMIN_ITEM_ADD_WEAPON_MELEE,
    ADMIN_ITEM_ADD_WEAPON_PROJECTILE,
    ADMIN_ITEM_ADD_WEAPON_GUN,

    ROOM_LIST_MENU,
    ROOM_JOIN_OK,
    GAME_RECORD,
    RECORD_LIST,
    RANKING_LIST

}
