package cn.lanink.gunwar.ui;

public enum GuiType {
    USER_MENU,
    ADMIN_MENU,
    ADMIN_TIME_MENU,
    ADMIN_PLAYERS_MENU,
    ADMIN_MODE_MENU,

    ADMIN_ITEM_ADD_WEAPON,
    ADMIN_ITEM_ADD_WEAPON_MELEE,

    ROOM_LIST_MENU,
    ROOM_JOIN_OK,
    GAME_RECORD,
    RECORD_LIST,
    RANKING_LIST

}
